# Generated by Django 5.2.3 on 2025-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0002_alter_product_price_alter_product_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фотография'),
        ),
    ]
